### ISSUE TITLE
Access to this repository

### ISSUE THREAD

**Issue by AndrewPaulChester** [ssardina-teaching/connect4p-base#9]
Hi @ssardina  - I have just realised I don't have write access to this repository (at least on this account - I don't have access to my staff account any more). 

What that also has made me realise is that this repo is public, not sure if that's intentional or not.

**Comment by ssardina** [comment]
Hi @AndrewPaulChester . ops, OK I just gave you maintain access. 

yes it is public, it is the base system, the template system where you build your solution. Makes sense?
